# Generated by Django 4.1.1 on 2022-09-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('product_details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_details',
            new_name='ProductCategory_details',
        ),
    ]
