# Generated by Django 4.1.1 on 2022-09-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_category_products_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
